// SPDX-License-Identifier: MIT
pragma solidity ^0.8.25;

import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import {AaveV3ArbitrumSepolia, AaveV3ArbitrumSepoliaAssets} from "aave-address-book/AaveV3ArbitrumSepolia.sol";
import {IPool} from "aave-v3-origin/contracts/interfaces/IPool.sol";
import {IAToken} from "aave-v3-origin/contracts/interfaces/IAToken.sol";
import {SafeERC20} from "aave-v3-origin/contracts/dependencies/openzeppelin/contracts/SafeERC20.sol";
import {IWrappedTokenGatewayV3} from "aave-v3-origin/contracts/helpers/interfaces/IWrappedTokenGatewayV3.sol";
import {IWETH} from "aave-v3-origin/contracts/helpers/interfaces/IWETH.sol";
import {Math} from "@openzeppelin/contracts/utils/math/Math.sol";

/**
 * @title BountyPool
 * @author Gustavo Figueiredo
 * @dev
 * - Accept ETH deposits from participants
 * - Allow users to specify yield allocation (e.g: 70% personal returns, 30% to bounties)
 * - Send ETH to a DeFi protocol (e.g: Aave) to generate yield
 * - Track individual staker contributions and their split preferences
 * - Distribute generated yield according to each staker's allocation
 */
contract BountyPool is ReentrancyGuard {
    using SafeERC20 for IAToken;
    using Math for uint256;

    /*//////////////////////////////////////////////////////////////
                    TYPE DECLARATIONS
    //////////////////////////////////////////////////////////////*/

    struct Deposit {
        uint256 amount;
        uint256 allocation;
        uint256 timestamp;
        uint256 yield;
    }

    /*//////////////////////////////////////////////////////////////
                    STATE VARIABLES
    //////////////////////////////////////////////////////////////*/
    /// @notice Pool Identifiers
    address private immutable bountyManager;
    uint256 private immutable id;
    string private name;
    string private imageUrl;

    /// @notice Pool
    IPool private immutable arbitrumSepoliaPool;
    /// @notice Gateway between the pool and WETH token
    IWrappedTokenGatewayV3 private immutable arbitrumSepoliaWETHGateway;
    /// @notice aToken
    IAToken private immutable aToken;

    /// @notice Current funds deposited in the pool
    uint256 private currentContributions;
    /// @notice Current bounty yield generated by the pool
    uint256 private currentBountyYield;
    /// @notice Current personal share of the total yield
    uint256 private currentContributorYield;
    /// @notice Current principal portion of aToken balance (tracks aToken balance considered as principal)
    uint256 private principalATokenBalance;

    /// @notice Last distributed aToken balance
    uint256 private lastYieldDistributionBalance;

    /// @notice Constants
    uint256 private constant MAX_YIELD_ALLOCATION = 100;
    uint256 private constant MIN_YIELD_ALLOCATION = 25;
    uint256 private constant LOCKUP_PERIOD = 90 days;
    uint256 private constant ALLOCATION_PERCENTAGE_BASE = 1e18;
    // 5% expressed in WAD (5 * 10^16)
    uint256 private constant EARLY_WITHDRAWAL_FEE_PERCENTAGE = 5e16;

    /// @notice Tolerance in wei to treat as rounding dust (≈0.00005 ETH)
    uint256 private constant ROUNDING_TOLERANCE = 5e13;

    /// @notice Array of contributors
    address[] public contributors;
    /// @notice Mapping of contributor deposits
    mapping(address => Deposit[]) public addressToContributorDeposits;
    /// @notice Mapping of last withdrawal timestamp
    mapping(address => uint256) public lastWithdrawalTimestamp;

    /*//////////////////////////////////////////////////////////////
                    EVENTS
    //////////////////////////////////////////////////////////////*/
    event Deposited(address indexed contributor, uint256 indexed amount, uint256 indexed allocation);
    event YieldWithdrawn(address indexed contributor, uint256 indexed amount, uint256 indexed depositIndex);
    event YieldDistributed(uint256 indexed bountyYield, uint256 indexed contributorYield);
    event BountyFunded(uint256 indexed bountyId, uint256 indexed amount);
    event PrincipalWithdrawn(address indexed contributor, uint256 indexed amount, uint256 indexed depositIndex);

    /*//////////////////////////////////////////////////////////////
                    ERRORS
    //////////////////////////////////////////////////////////////*/
    error BountyPool__InvalidYieldAllocation();
    error BountyPool__MustDepositSomeETH();
    error BountyPool__NotBountyManager();
    error BountyPool__NotEnoughBountyYield();
    error BountyPool__InvalidDepositIndex();
    error BountyPool__NoPrincipalToWithdraw();
    error BountyPool__NoYieldToWithdraw();
    error BountyPool__WETHGatewayNotInitialized();
    error BountyPool__WithdrawalFailed();
    error BountyPool__InsufficientATokenBalance();
    error BountyPool__WithdrawalTemporarilyUnavailable();

    /*//////////////////////////////////////////////////////////////
                    MODIFIERS
    //////////////////////////////////////////////////////////////*/

    modifier onlyIfBountyManager() {
        if (msg.sender != bountyManager) revert BountyPool__NotBountyManager();
        _;
    }

    /*//////////////////////////////////////////////////////////////
                    FUNCTIONS
    //////////////////////////////////////////////////////////////*/
    constructor(address _bountyManager, uint256 _id, string memory _name, string memory _imageUrl) {
        bountyManager = _bountyManager;
        id = _id;
        name = _name;
        imageUrl = _imageUrl;

        arbitrumSepoliaPool = IPool(AaveV3ArbitrumSepolia.POOL);
        arbitrumSepoliaWETHGateway = IWrappedTokenGatewayV3(AaveV3ArbitrumSepolia.WETH_GATEWAY);
        aToken = IAToken(AaveV3ArbitrumSepoliaAssets.WETH_A_TOKEN);
        aToken.safeIncreaseAllowance(address(arbitrumSepoliaPool), type(uint256).max);

        principalATokenBalance = 0;
        currentContributions = 0;
        currentBountyYield = 0;
        currentContributorYield = 0;
        lastYieldDistributionBalance = 0;
    }

    receive() external payable {}

    /**
     * @notice Deposit ETH into the pool
     * @param allocation The percentage of yield to allocate to bounties
     * @dev The allocation must be between 25% and 100%, otherwise it wouldn't make sense to use this protocol.
     */
    function deposit(uint256 allocation) external payable nonReentrant {
        if (allocation > MAX_YIELD_ALLOCATION || allocation < MIN_YIELD_ALLOCATION) {
            revert BountyPool__InvalidYieldAllocation();
        }
        if (msg.value == 0) revert BountyPool__MustDepositSomeETH();

        Deposit[] storage contributorDeposits = addressToContributorDeposits[msg.sender];
        if (contributorDeposits.length == 0) {
            contributors.push(msg.sender);
        }
        // Scale the user-supplied percentage (0-100) to WAD (0-1e18)
        uint256 scaledAllocation = (allocation * ALLOCATION_PERCENTAGE_BASE) / 100;

        contributorDeposits.push(
            Deposit({amount: msg.value, allocation: scaledAllocation, timestamp: block.timestamp, yield: 0})
        );

        if (address(arbitrumSepoliaWETHGateway) == address(0)) {
            revert BountyPool__WETHGatewayNotInitialized();
        }

        currentContributions += msg.value;
        principalATokenBalance += msg.value;

        emit Deposited(msg.sender, msg.value, allocation);

        arbitrumSepoliaWETHGateway.depositETH{value: msg.value}(address(arbitrumSepoliaPool), address(this), 0);
        lastYieldDistributionBalance = aToken.balanceOf(address(this));
    }

    /**
     * @notice Fund a bounty
     * @param _bountyId The ID of the bounty to fund
     * @param amount The amount of ETH to fund the bounty
     * @dev This is only called by the BountyManager.
     * @dev aave -> bountymanager
     */
    function fundBounty(uint256 _bountyId, uint256 amount)
        external
        nonReentrant
        onlyIfBountyManager
        returns (uint256)
    {
        // Refresh tracked yield ONLY if needed to cover the requested amount.
        if (currentBountyYield < amount) {
            _distributeYield();
            if (currentBountyYield < amount) revert BountyPool__NotEnoughBountyYield();
        }

        currentBountyYield -= amount;

        uint256 aTokenBalance = aToken.balanceOf(address(this));
        if (aTokenBalance < amount) {
            revert BountyPool__InsufficientATokenBalance();
        }

        emit BountyFunded(_bountyId, amount);

        // aderyn-ignore-next-line(reentrancy-state-change)
        uint256 withdrawnAmount =
            arbitrumSepoliaPool.withdraw(AaveV3ArbitrumSepoliaAssets.WETH_UNDERLYING, amount, address(this));

        lastYieldDistributionBalance = aToken.balanceOf(address(this));

        IWETH weth = IWETH(AaveV3ArbitrumSepoliaAssets.WETH_UNDERLYING);
        weth.withdraw(withdrawnAmount);

        (bool success,) = payable(bountyManager).call{value: withdrawnAmount}("");
        if (!success) revert BountyPool__WithdrawalFailed();

        return withdrawnAmount;
    }

    /**
     * @notice Withdraw the yield generated by the pool for a specific deposit.
     * @param depositId The index of the deposit to withdraw the yield from
     * @dev aave -> bountypool -> user
     */
    function withdrawYield(uint256 depositId) external nonReentrant {
        _distributeYield();

        Deposit[] storage deposits = addressToContributorDeposits[msg.sender];
        if (depositId >= deposits.length) revert BountyPool__InvalidDepositIndex();

        Deposit storage contributorDeposit = deposits[depositId];
        uint256 yieldAmount = contributorDeposit.yield;
        if (yieldAmount == 0) revert BountyPool__NoYieldToWithdraw();

        lastWithdrawalTimestamp[msg.sender] = block.timestamp;
        emit YieldWithdrawn(msg.sender, yieldAmount, depositId);

        // aderyn-ignore-next-line(reentrancy-state-change)
        uint256 withdrawnAmount =
            arbitrumSepoliaPool.withdraw(AaveV3ArbitrumSepoliaAssets.WETH_UNDERLYING, yieldAmount, address(this));

        uint256 newATokenBalance = aToken.balanceOf(address(this));
        lastYieldDistributionBalance = newATokenBalance;

        contributorDeposit.yield = 0;
        currentContributorYield -= yieldAmount;

        uint256 trackedYield = currentBountyYield + currentContributorYield;
        _adjust(trackedYield, newATokenBalance);

        IWETH weth = IWETH(AaveV3ArbitrumSepoliaAssets.WETH_UNDERLYING);
        weth.withdraw(withdrawnAmount);

        (bool success,) = payable(msg.sender).call{value: withdrawnAmount}("");
        if (!success) revert BountyPool__WithdrawalFailed();
    }

    /**
     * @notice Withdraw the principal amount deposited by the contributor.
     * @param depositId The index of the deposit to withdraw the principal from
     * @dev aave -> bountypool -> user
     */
    function withdrawPrincipal(uint256 depositId) external nonReentrant {
        _distributeYield();

        Deposit[] storage deposits = addressToContributorDeposits[msg.sender];
        if (depositId >= deposits.length) revert BountyPool__InvalidDepositIndex();

        Deposit storage contributorDeposit = deposits[depositId];
        uint256 totalAmount = contributorDeposit.amount;
        if (totalAmount == 0) revert BountyPool__NoPrincipalToWithdraw();

        uint256 withdrawableAmount = totalAmount;
        if (!_checkLockupPeriodPassed(depositId)) {
            uint256 scaledFee = Math.mulDiv(totalAmount, EARLY_WITHDRAWAL_FEE_PERCENTAGE, ALLOCATION_PERCENTAGE_BASE);
            withdrawableAmount -= scaledFee;
            currentBountyYield += scaledFee;
        }

        contributorDeposit.amount = 0;
        currentContributions -= totalAmount;

        if (principalATokenBalance >= totalAmount) {
            principalATokenBalance -= totalAmount;
        } else {
            principalATokenBalance = 0;
        }

        emit PrincipalWithdrawn(msg.sender, withdrawableAmount, depositId);
        // aderyn-ignore-next-line(reentrancy-state-change)
        uint256 withdrawnAmount =
            arbitrumSepoliaPool.withdraw(AaveV3ArbitrumSepoliaAssets.WETH_UNDERLYING, withdrawableAmount, address(this));

        uint256 newATokenBalance = aToken.balanceOf(address(this));
        lastYieldDistributionBalance = newATokenBalance;

        uint256 trackedYield = currentBountyYield + currentContributorYield;
        _adjust(trackedYield, newATokenBalance);

        IWETH weth = IWETH(AaveV3ArbitrumSepoliaAssets.WETH_UNDERLYING);
        weth.withdraw(withdrawnAmount);

        (bool success,) = payable(msg.sender).call{value: withdrawnAmount}("");
        if (!success) revert BountyPool__WithdrawalFailed();
    }

    /**
     * @notice Distribute the yield generated by the pool. This updates the yield values
     * but doesn't withdraw anything from AAVE.
     * @dev This is only called by the BountyManager.
     */
    function distributeYield() external nonReentrant onlyIfBountyManager {
        _distributeYield();
    }

    /*//////////////////////////////////////////////////////////////
                    INTERNAL FUNCTIONS
    //////////////////////////////////////////////////////////////*/
    /**
     * @notice Distributes the yield generated by the pool, updating state variables.
     * @dev High Risk: This function will get costly with time if the pool has many contributors
     *                 Consider alternatives.
     */
    function _distributeYield() internal {
        uint256 currentATokenBalance = aToken.balanceOf(address(this));
        if (principalATokenBalance == 0) {
            return;
        }

        uint256 newYieldEarned = currentATokenBalance > lastYieldDistributionBalance
            ? currentATokenBalance - lastYieldDistributionBalance
            : 0;
        if (newYieldEarned == 0) return;

        uint256 totalWeightedAllocation = 0;
        uint256 totalPersonalAllocation = 0;
        uint256 contributorsLength = contributors.length;

        /// @dev Calculate total weighted and personal allocations
        for (uint256 i = 0; i < contributorsLength; i++) {
            Deposit[] memory contributorDeposits = addressToContributorDeposits[contributors[i]];
            for (uint256 j = 0; j < contributorDeposits.length; j++) {
                if (contributorDeposits[j].amount > 0) {
                    // Keep full‑precision numerator (amount * allocation)
                    uint256 weightedAmount = contributorDeposits[j].amount * contributorDeposits[j].allocation;
                    totalWeightedAllocation += weightedAmount;

                    uint256 personalAmount =
                        contributorDeposits[j].amount * (ALLOCATION_PERCENTAGE_BASE - contributorDeposits[j].allocation);
                    totalPersonalAllocation += personalAmount;
                }
            }
        }

        uint256 bountyShare;
        uint256 contributorShare;

        if (totalWeightedAllocation == 0) {
            bountyShare = newYieldEarned;
            contributorShare = 0;
        } else if (currentContributions == 0) {
            bountyShare = newYieldEarned;
            contributorShare = 0;
        } else {
            uint256 denominator = currentContributions * ALLOCATION_PERCENTAGE_BASE;
            bountyShare = Math.mulDiv(newYieldEarned, totalWeightedAllocation, denominator);
            if (bountyShare > newYieldEarned) {
                bountyShare = newYieldEarned;
            }
            contributorShare = Math.mulDiv(newYieldEarned, totalPersonalAllocation, denominator);
        }

        // Ensure we distribute the *entire* newYieldEarned – send any remainder to the bounty bucket.
        uint256 distributed = bountyShare + contributorShare;
        if (distributed < newYieldEarned) {
            bountyShare += newYieldEarned - distributed;
        }

        currentBountyYield += bountyShare;
        currentContributorYield += contributorShare;

        if (contributorShare > 0 && totalPersonalAllocation > 0) {
            for (uint256 i = 0; i < contributorsLength; i++) {
                Deposit[] storage contributorDeposits = addressToContributorDeposits[contributors[i]];
                for (uint256 j = 0; j < contributorDeposits.length; j++) {
                    if (contributorDeposits[j].amount > 0) {
                        uint256 personalAllocation = contributorDeposits[j].amount
                            * (ALLOCATION_PERCENTAGE_BASE - contributorDeposits[j].allocation);

                        uint256 personalYield =
                            Math.mulDiv(contributorShare, personalAllocation, totalPersonalAllocation);

                        contributorDeposits[j].yield += personalYield;
                    }
                }
            }
        }

        emit YieldDistributed(bountyShare, contributorShare);
    }

    /**
     * @notice Adjusts yield accounting to ensure tracked yield doesn't exceed actual aToken balance
     * @param trackedYield The total tracked yield (bounty + contributor)
     * @param newATokenBalance The current aToken balance
     * @return The adjusted tracked yield
     */
    function _adjust(uint256 trackedYield, uint256 newATokenBalance) internal returns (uint256) {
        // If tracked yield is greater than actual balance, trim proportionally
        if (trackedYield > newATokenBalance) {
            // Apply a small rounding adjustment to ensure invariant holds
            uint256 adjustment = trackedYield - newATokenBalance;

            // Adjust bounty and contributor yields proportionally based on their current values
            if (currentBountyYield > 0 && currentContributorYield > 0) {
                uint256 bountyAdjustment = (adjustment * currentBountyYield) / trackedYield;
                uint256 contributorAdjustment = adjustment - bountyAdjustment;

                currentBountyYield -= bountyAdjustment;
                currentContributorYield -= contributorAdjustment;
            } else if (currentBountyYield > 0) {
                currentBountyYield = newATokenBalance;
            } else if (currentContributorYield > 0) {
                currentContributorYield = newATokenBalance;
            }

            return newATokenBalance;
        } else {
            // trackedYield <= newATokenBalance. If the gap is within tolerance, treat as dust and keep invariants.
            uint256 gap = newATokenBalance - trackedYield;
            if (gap <= ROUNDING_TOLERANCE) {
                // Ignore insignificant dust to avoid artificially inflating bounty yield
                // We simply keep the existing tracked values untouched, ensuring they
                // never exceed the actual aToken balance while preventing unexpected
                // yield increases that break UI expectations and downstream logic.
                return newATokenBalance;
            }
        }

        return trackedYield;
    }

    /**
     * @notice Check if the lockup period has passed for a specific deposit.
     * @param depositId The index of the deposit to check the lockup period for
     * @return true if the lockup period has passed, false otherwise
     */
    function _checkLockupPeriodPassed(uint256 depositId) internal view returns (bool) {
        Deposit storage contributorDeposit = addressToContributorDeposits[msg.sender][depositId];
        if (block.timestamp < contributorDeposit.timestamp + LOCKUP_PERIOD) {
            return false;
        }
        return true;
    }

    /*//////////////////////////////////////////////////////////////
                    PUBLIC AND EXTERNAL VIEW FUNCTIONS
    //////////////////////////////////////////////////////////////*/
    /**
     * @notice Calculates the total available bounty yield, including untracked yield from AAVE.
     * @return The total available bounty yield in wei.
     */
    function getAvailableBountyYield() external view returns (uint256) {
        uint256 currentATokenBalance = aToken.balanceOf(address(this));
        if (principalATokenBalance == 0) {
            return currentATokenBalance;
        }
        uint256 trackedYield = currentBountyYield;

        if (currentATokenBalance <= lastYieldDistributionBalance) {
            return trackedYield;
        }

        /// @dev Calculate new yield based on the difference from last distribution balance
        uint256 newYieldEarned = currentATokenBalance - lastYieldDistributionBalance;

        if (newYieldEarned == 0) {
            return trackedYield;
        }

        uint256 totalWeightedAllocation = 0;
        uint256 contributorsLength = contributors.length;

        for (uint256 i = 0; i < contributorsLength; i++) {
            Deposit[] memory contributorDeposits = addressToContributorDeposits[contributors[i]];
            for (uint256 j = 0; j < contributorDeposits.length; j++) {
                if (contributorDeposits[j].amount > 0) {
                    totalWeightedAllocation += contributorDeposits[j].amount * contributorDeposits[j].allocation;
                }
            }
        }

        /// @dev Calculate the percentage of total yield that should go to bounties
        uint256 bountyShare;
        if (totalWeightedAllocation == 0) {
            bountyShare = 0;
        } else if (currentContributions == 0) {
            bountyShare = newYieldEarned;
        } else {
            uint256 denominator2 = currentContributions * ALLOCATION_PERCENTAGE_BASE;
            bountyShare = Math.mulDiv(newYieldEarned, totalWeightedAllocation, denominator2);
            if (bountyShare > newYieldEarned) {
                bountyShare = newYieldEarned;
            }
        }

        return trackedYield + bountyShare;
    }

    /**
     * @notice Returns the currently distributed bounty yield (excludes untracked AAVE yield).
     * @dev Use getAvailableBountyYield for the total available yield, including untracked yield.
     * @return The distributed bounty yield in wei.
     */
    function getCurrentBountyYield() external view returns (uint256) {
        return currentBountyYield;
    }

    /**
     * @notice Calculates the total available yield for a specific contributor, including untracked yield from AAVE.
     * @param contributor The address of the contributor
     * @return The total available yield for the contributor in wei
     */
    function getAvailableContributorYield(address contributor) external view returns (uint256) {
        uint256 currentBalance = aToken.balanceOf(address(this));

        if (principalATokenBalance == 0) {
            return _getTrackedContributorYield(contributor);
        }

        uint256 trackedYield = _getTrackedContributorYield(contributor);

        if (currentBalance <= lastYieldDistributionBalance) {
            return trackedYield;
        }

        /// @dev Calculate new yield based on the difference from last distribution balance
        uint256 newYieldEarned = currentBalance - lastYieldDistributionBalance;

        if (newYieldEarned == 0) {
            return trackedYield;
        }

        uint256 totalWeightedAllocation = 0;
        uint256 totalPersonalAllocation = 0;
        uint256 contributorsLength = contributors.length;

        /// @dev Calculate total weighted and personal allocations
        for (uint256 i = 0; i < contributorsLength; i++) {
            Deposit[] memory allDeposits = addressToContributorDeposits[contributors[i]];
            for (uint256 j = 0; j < allDeposits.length; j++) {
                if (allDeposits[j].amount > 0) {
                    totalWeightedAllocation += allDeposits[j].amount * allDeposits[j].allocation;
                    totalPersonalAllocation +=
                        allDeposits[j].amount * (ALLOCATION_PERCENTAGE_BASE - allDeposits[j].allocation);
                }
            }
        }

        if (totalPersonalAllocation == 0 || totalWeightedAllocation == 0) {
            return trackedYield;
        }

        /// @dev Calculate the contributor's share of the new yield
        uint256 contributorPersonalAllocation = 0;
        Deposit[] memory contributorDeposits = addressToContributorDeposits[contributor];

        for (uint256 i = 0; i < contributorDeposits.length; i++) {
            if (contributorDeposits[i].amount > 0) {
                contributorPersonalAllocation +=
                    contributorDeposits[i].amount * (ALLOCATION_PERCENTAGE_BASE - contributorDeposits[i].allocation);
            }
        }
        uint256 denominator3 = currentContributions * ALLOCATION_PERCENTAGE_BASE;
        uint256 bountyShare = Math.mulDiv(newYieldEarned, totalWeightedAllocation, denominator3);
        if (bountyShare > newYieldEarned) {
            bountyShare = newYieldEarned;
        }

        uint256 totalPersonalYield = newYieldEarned - bountyShare;

        uint256 contributorShare = 0;
        if (totalPersonalAllocation > 0 && contributorPersonalAllocation > 0) {
            contributorShare = Math.mulDiv(totalPersonalYield, contributorPersonalAllocation, totalPersonalAllocation);
        }

        return trackedYield + contributorShare;
    }

    /**
     * @notice Helper function to get the tracked yield for a contributor
     * @param contributor The address of the contributor
     * @return The tracked yield for the contributor in wei
     */
    function _getTrackedContributorYield(address contributor) internal view returns (uint256) {
        uint256 trackedYield = 0;
        Deposit[] memory contributorDeposits = addressToContributorDeposits[contributor];

        for (uint256 j = 0; j < contributorDeposits.length; j++) {
            trackedYield += contributorDeposits[j].yield;
        }

        return trackedYield;
    }

    function getId() external view returns (uint256) {
        return id;
    }

    function getName() external view returns (string memory) {
        return name;
    }

    function getImageUrl() external view returns (string memory) {
        return imageUrl;
    }

    function getCurrentContributions() external view returns (uint256) {
        return currentContributions;
    }

    function getCurrentContributorYield() external view returns (uint256) {
        return currentContributorYield;
    }

    function getContributors() external view returns (address[] memory) {
        return contributors;
    }

    function getContributorDeposits(address contributor) external view returns (Deposit[] memory) {
        return addressToContributorDeposits[contributor];
    }

    function getLastWithdrawalTimestamp(address contributor) external view returns (uint256) {
        return lastWithdrawalTimestamp[contributor];
    }
}
